#RUN
#grep -src 'PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>PRO-HLII
grep -src 'aapJ-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>aapJ-PRO-HLII
grep -src 'aapJ-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>aapJ-PRO-HLIx
grep -src 'aapJ-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>aapJ-PRO-HLVI
grep -src 'aapJ-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>aapJ-PRO-LLIIxIII
grep -src 'aapJ-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>aapJ-PRO-LLIV
grep -src 'aapJ-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>aapJ-PRO-LLIx
grep -src 'aapJ-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>aapJ-SYN
grep -src 'amt1-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>amt1-PRO-HLII
grep -src 'amt1-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>amt1-PRO-HLIx
grep -src 'amt1-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>amt1-PRO-HLVI
grep -src 'amt1-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>amt1-PRO-LLIIxIII
grep -src 'amt1-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>amt1-PRO-LLIV
grep -src 'amt1-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>amt1-PRO-LLIx
grep -src 'amt1-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>amt1-SYN
grep -src 'CAD-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>CAD-PRO-HLII
grep -src 'CAD-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>CAD-PRO-HLIx
grep -src 'CAD-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>CAD-PRO-HLVI
grep -src 'CAD-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>CAD-PRO-LLIIxIII
grep -src 'CAD-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>CAD-PRO-LLIV
grep -src 'CAD-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>CAD-PRO-LLIx
grep -src 'CAD-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>CAD-SYN
grep -src 'carA-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>carA-PRO-HLII
grep -src 'carA-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>carA-PRO-HLIx
grep -src 'carA-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>carA-PRO-HLVI
grep -src 'carA-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>carA-PRO-LLIIxIII
grep -src 'carA-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>carA-PRO-LLIV
grep -src 'carA-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>carA-PRO-LLIx
grep -src 'carA-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>carA-SYN
grep -src 'carB-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>carB-PRO-HLII
grep -src 'carB-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>carB-PRO-HLIx
grep -src 'carB-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>carB-PRO-HLVI
grep -src 'carB-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>carB-PRO-LLIIxIII
grep -src 'carB-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>carB-PRO-LLIV
grep -src 'carB-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>carB-PRO-LLIx
grep -src 'carB-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>carB-SYN
grep -src 'cbbL-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>cbbL-PRO-HLII
grep -src 'cbbL-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>cbbL-PRO-HLIx
grep -src 'cbbL-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>cbbL-PRO-HLVI
grep -src 'cbbL-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>cbbL-PRO-LLIIxIII
grep -src 'cbbL-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>cbbL-PRO-LLIV
grep -src 'cbbL-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>cbbL-PRO-LLIx
grep -src 'cbbL-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>cbbL-SYN
grep -src 'cbbS-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>cbbS-PRO-HLII
grep -src 'cbbS-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>cbbS-PRO-HLIx
grep -src 'cbbS-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>cbbS-PRO-HLVI
grep -src 'cbbS-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>cbbS-PRO-LLIIxIII
grep -src 'cbbS-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>cbbS-PRO-LLIV
grep -src 'cbbS-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>cbbS-PRO-LLIx
grep -src 'cbbS-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>cbbS-SYN
grep -src 'CcmK-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>CcmK-PRO-HLII
grep -src 'CcmK-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>CcmK-PRO-HLIx
grep -src 'CcmK-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>CcmK-PRO-HLVI
grep -src 'CcmK-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>CcmK-PRO-LLIIxIII
grep -src 'CcmK-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>CcmK-PRO-LLIV
grep -src 'CcmK-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>CcmK-PRO-LLIx
grep -src 'CcmK-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>CcmK-SYN
grep -src 'ClpB-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>ClpB-PRO-HLII
grep -src 'ClpB-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>ClpB-PRO-HLIx
grep -src 'ClpB-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>ClpB-PRO-HLVI
grep -src 'ClpB-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>ClpB-PRO-LLIIxIII
grep -src 'ClpB-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>ClpB-PRO-LLIV
grep -src 'ClpB-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>ClpB-PRO-LLIx
grep -src 'ClpB-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>ClpB-SYN
grep -src 'CLP-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>CLP-PRO-HLII
grep -src 'CLP-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>CLP-PRO-HLIx
grep -src 'CLP-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>CLP-PRO-HLVI
grep -src 'CLP-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>CLP-PRO-LLIIxIII
grep -src 'CLP-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>CLP-PRO-LLIV
grep -src 'CLP-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>CLP-PRO-LLIx
grep -src 'CLP-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>CLP-SYN
grep -src 'cynA-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>cynA-PRO-HLII
grep -src 'cynA-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>cynA-PRO-HLIx
grep -src 'cynA-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>cynA-SYN
grep -src 'CysA-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>CysA-PRO-HLII
grep -src 'CysA-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>CysA-PRO-HLIx
grep -src 'CysA-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>CysA-PRO-LLIx
grep -src 'CysA-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>CysA-SYN
grep -src 'CysT-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>CysT-SYN
grep -src 'CysW-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>CysW-SYN
grep -src 'dnaJ-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>dnaJ-PRO-HLII
grep -src 'dnaJ-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>dnaJ-PRO-HLIx
grep -src 'dnaJ-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>dnaJ-PRO-HLVI
grep -src 'dnaJ-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>dnaJ-PRO-LLIIxIII
grep -src 'dnaJ-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>dnaJ-PRO-LLIV
grep -src 'dnaJ-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>dnaJ-PRO-LLIx
grep -src 'dnaJ-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>dnaJ-SYN
grep -src 'dnaK1-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>dnaK1-PRO-HLII
grep -src 'dnaK1-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>dnaK1-PRO-HLIx
grep -src 'dnaK1-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>dnaK1-PRO-HLVI
grep -src 'dnaK1-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>dnaK1-PRO-LLIIxIII
grep -src 'dnaK1-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>dnaK1-PRO-LLIV
grep -src 'dnaK1-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>dnaK1-PRO-LLIx
grep -src 'dnaK1-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>dnaK1-SYN
grep -src 'dnaK2-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>dnaK2-PRO-HLII
grep -src 'dnaK2-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>dnaK2-PRO-HLIx
grep -src 'dnaK2-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>dnaK2-PRO-HLVI
grep -src 'dnaK2-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>dnaK2-PRO-LLIIxIII
grep -src 'dnaK2-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>dnaK2-PRO-LLIV
grep -src 'dnaK2-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>dnaK2-PRO-LLIx
grep -src 'dnaK2-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>dnaK2-SYN
grep -src 'dnaN1-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>dnaN1-PRO-HLII
grep -src 'dnaN1-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>dnaN1-PRO-HLIx
grep -src 'dnaN1-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>dnaN1-PRO-HLVI
grep -src 'dnaN1-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>dnaN1-PRO-LLIIxIII
grep -src 'dnaN1-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>dnaN1-PRO-LLIV
grep -src 'dnaN1-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>dnaN1-PRO-LLIx
grep -src 'dnaN1-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>dnaN1-SYN
grep -src 'FbpC-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>FbpC-PRO-HLII
grep -src 'FbpC-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>FbpC-PRO-HLIx
grep -src 'FbpC-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>FbpC-PRO-HLVI
grep -src 'FbpC-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>FbpC-PRO-LLIIxIII
grep -src 'FbpC-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>FbpC-PRO-LLIV
grep -src 'FbpC-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>FbpC-PRO-LLIx
grep -src 'FbpC-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>FbpC-SYN
grep -src 'focA-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>focA-PRO-LLIIxIII
grep -src 'focA-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>focA-PRO-LLIV
grep -src 'focA-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>focA-PRO-LLIx
grep -src 'focA-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>focA-SYN
grep -src 'FutA-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>FutA-PRO-HLII
grep -src 'FutA-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>FutA-PRO-HLIx
grep -src 'FutA-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>FutA-PRO-LLIIxIII
grep -src 'FutA-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>FutA-PRO-LLIx
grep -src 'FutA-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>FutA-SYN
grep -src 'GlmS-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>GlmS-PRO-HLII
grep -src 'GlmS-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>GlmS-PRO-HLIx
grep -src 'GlmS-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>GlmS-PRO-HLVI
grep -src 'GlmS-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>GlmS-PRO-LLIIxIII
grep -src 'GlmS-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>GlmS-PRO-LLIV
grep -src 'GlmS-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>GlmS-PRO-LLIx
grep -src 'GlmS-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>GlmS-SYN
grep -src 'glnA-PRO-HLI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>glnA-PRO-HLI
grep -src 'glnA-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>glnA-PRO-HLII
grep -src 'glnA-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>glnA-PRO-HLVI
grep -src 'glnA-PRO-LLI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>glnA-PRO-LLI
grep -src 'glnA-PRO-LLII/III' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>glnA-PRO-LLII/III
grep -src 'glnA-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>glnA-PRO-LLIV
grep -src 'glnA-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>glnA-SYN
grep -src 'glnH-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>glnH-SYN
grep -src 'glnQ-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>glnQ-PRO-HLII
grep -src 'glnQ-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>glnQ-PRO-HLIx
grep -src 'glnQ-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>glnQ-PRO-HLVI
grep -src 'glnQ-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>glnQ-PRO-LLIIxIII
grep -src 'glnQ-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>glnQ-PRO-LLIV
grep -src 'glnQ-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>glnQ-PRO-LLIx
grep -src 'glnQ-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>glnQ-SYN
grep -src 'gltJ-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>gltJ-PRO-HLII
grep -src 'gltJ-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>gltJ-PRO-HLIx
grep -src 'gltJ-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>gltJ-PRO-HLVI
grep -src 'gltJ-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>gltJ-PRO-LLIIxIII
grep -src 'gltJ-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>gltJ-PRO-LLIV
grep -src 'gltJ-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>gltJ-PRO-LLIx
grep -src 'gltJ-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>gltJ-SYN
grep -src 'groEL1-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>groEL1-PRO-HLII
grep -src 'groEL1-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>groEL1-PRO-HLIx
grep -src 'groEL1-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>groEL1-PRO-HLVI
grep -src 'groEL1-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>groEL1-PRO-LLIIxIII
grep -src 'groEL1-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>groEL1-PRO-LLIV
grep -src 'groEL1-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>groEL1-PRO-LLIx
grep -src 'groEL1-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>groEL1-SYN
grep -src 'groEL2-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>groEL2-PRO-HLII
grep -src 'groEL2-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>groEL2-PRO-HLIx
grep -src 'groEL2-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>groEL2-PRO-HLVI
grep -src 'groEL2-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>groEL2-PRO-LLIIxIII
grep -src 'groEL2-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>groEL2-PRO-LLIV
grep -src 'groEL2-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>groEL2-PRO-LLIx
grep -src 'groEL2-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>groEL2-SYN
grep -src 'groES-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>groES-PRO-HLII
grep -src 'groES-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>groES-PRO-HLIx
grep -src 'groES-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>groES-PRO-HLVI
grep -src 'groES-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>groES-PRO-LLIIxIII
grep -src 'groES-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>groES-PRO-LLIV
grep -src 'groES-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>groES-PRO-LLIx
grep -src 'groES-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>groES-SYN
grep -src 'GrpE-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>GrpE-PRO-HLII
grep -src 'GrpE-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>GrpE-PRO-HLIx
grep -src 'GrpE-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>GrpE-PRO-HLVI
grep -src 'GrpE-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>GrpE-PRO-LLIIxIII
grep -src 'GrpE-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>GrpE-PRO-LLIV
grep -src 'GrpE-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>GrpE-PRO-LLIx
grep -src 'GrpE-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>GrpE-SYN
grep -src 'hpsA-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>hpsA-SYN
grep -src 'HtpG-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>HtpG-PRO-HLII
grep -src 'HtpG-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>HtpG-PRO-HLIx
grep -src 'HtpG-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>HtpG-PRO-HLVI
grep -src 'HtpG-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>HtpG-PRO-LLIIxIII
grep -src 'HtpG-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>HtpG-PRO-LLIV
grep -src 'HtpG-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>HtpG-PRO-LLIx
grep -src 'HtpG-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>HtpG-SYN
grep -src 'icd-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>icd-PRO-HLII
grep -src 'icd-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>icd-PRO-HLIx
grep -src 'icd-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>icd-PRO-HLVI
grep -src 'icd-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>icd-PRO-LLIIxIII
grep -src 'icd-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>icd-PRO-LLIV
grep -src 'icd-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>icd-PRO-LLIx
grep -src 'icd-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>icd-SYN
grep -src 'idiA-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>idiA-PRO-HLII
grep -src 'idiA-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>idiA-PRO-HLIx
grep -src 'idiA-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>idiA-PRO-HLVI
grep -src 'idiA-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>idiA-PRO-LLIIxIII
grep -src 'idiA-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>idiA-PRO-LLIV
grep -src 'idiA-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>idiA-PRO-LLIx
grep -src 'idiA-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>idiA-SYN
grep -src 'LexA-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>LexA-PRO-HLII
grep -src 'LexA-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>LexA-PRO-HLIx
grep -src 'LexA-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>LexA-PRO-HLVI
grep -src 'LexA-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>LexA-PRO-LLIIxIII
grep -src 'LexA-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>LexA-PRO-LLIV
grep -src 'LexA-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>LexA-PRO-LLIx
grep -src 'LexA-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>LexA-SYN
grep -src 'LivF-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>LivF-PRO-HLII
grep -src 'LivF-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>LivF-PRO-HLIx
grep -src 'LivF-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>LivF-PRO-HLVI
grep -src 'LivF-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>LivF-PRO-LLIIxIII
grep -src 'LivF-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>LivF-PRO-LLIV
grep -src 'LivF-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>LivF-PRO-LLIx
grep -src 'LivF-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>LivF-SYN
grep -src 'livG-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>livG-SYN
grep -src 'LivH-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>LivH-PRO-HLII
grep -src 'LivH-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>LivH-PRO-HLIx
grep -src 'LivH-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>LivH-PRO-HLVI
grep -src 'LivH-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>LivH-PRO-LLIIxIII
grep -src 'LivH-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>LivH-PRO-LLIV
grep -src 'LivH-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>LivH-PRO-LLIx
grep -src 'LivH-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>LivH-SYN
grep -src 'livK-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>livK-SYN
grep -src 'livM-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>livM-SYN
grep -src 'metN2-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>metN2-PRO-HLII
grep -src 'metN2-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>metN2-PRO-HLIx
grep -src 'metN2-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>metN2-PRO-LLIIxIII
grep -src 'metN2-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>metN2-PRO-LLIV
grep -src 'metN2-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>metN2-PRO-LLIx
grep -src 'metN2-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>metN2-SYN
grep -src 'narB-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>narB-PRO-HLII
grep -src 'narB-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>narB-PRO-HLIx
grep -src 'narB-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>narB-PRO-HLVI
grep -src 'narB-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>narB-PRO-LLIx
grep -src 'narB-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>narB-SYN
grep -src 'natB-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>natB-SYN
grep -src 'nirA-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>nirA-PRO-HLII
grep -src 'nirA-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>nirA-PRO-HLIx
grep -src 'nirA-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>nirA-PRO-HLVI
grep -src 'nirA-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>nirA-PRO-LLIIxIII
grep -src 'nirA-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>nirA-PRO-LLIV
grep -src 'nirA-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>nirA-PRO-LLIx
grep -src 'nirA-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>nirA-SYN
grep -src 'nrtA-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>nrtA-SYN
grep -src 'nrtB-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>nrtB-PRO-HLII
grep -src 'nrtB-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>nrtB-PRO-HLIx
grep -src 'nrtB-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>nrtB-SYN
grep -src 'nrtC-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>nrtC-SYN
grep -src 'nrtP-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>nrtP-PRO-HLII
grep -src 'nrtP-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>nrtP-PRO-HLIx
grep -src 'nrtP-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>nrtP-PRO-HLVI
grep -src 'nrtP-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>nrtP-PRO-LLIx
grep -src 'nrtP-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>nrtP-SYN
grep -src 'ntcA-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>ntcA-PRO-HLII
grep -src 'ntcA-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>ntcA-PRO-HLIx
grep -src 'ntcA-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>ntcA-PRO-HLVI
grep -src 'ntcA-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>ntcA-PRO-LLIIxIII
grep -src 'ntcA-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>ntcA-PRO-LLIV
grep -src 'ntcA-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>ntcA-PRO-LLIx
grep -src 'ntcA-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>ntcA-SYN
grep -src 'OccM-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>OccM-PRO-HLII
grep -src 'OccM-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>OccM-PRO-HLVI
grep -src 'OccM-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>OccM-PRO-LLIIxIII
grep -src 'OccM-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>OccM-PRO-LLIx
grep -src 'petB-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>petB-PRO-HLII
grep -src 'petB-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>petB-PRO-HLIx
grep -src 'petB-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>petB-PRO-HLVI
grep -src 'petB-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>petB-PRO-LLIIxIII
grep -src 'petB-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>petB-PRO-LLIV
grep -src 'petB-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>petB-PRO-LLIx
grep -src 'petB-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>petB-SYN
grep -src 'PII-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>PII-PRO-HLII
grep -src 'PII-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>PII-PRO-HLIx
grep -src 'PII-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>PII-PRO-HLVI
grep -src 'PII-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>PII-PRO-LLIIxIII
grep -src 'PII-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>PII-PRO-LLIV
grep -src 'PII-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>PII-PRO-LLIx
grep -src 'PII-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>PII-SYN
grep -src 'polA-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>polA-PRO-HLII
grep -src 'polA-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>polA-PRO-HLIx
grep -src 'polA-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>polA-PRO-HLVI
grep -src 'polA-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>polA-PRO-LLIIxIII
grep -src 'polA-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>polA-PRO-LLIV
grep -src 'polA-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>polA-PRO-LLIx
grep -src 'polA-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>polA-SYN
grep -src 'psb28-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>psb28-PRO-HLII
grep -src 'psb28-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>psb28-PRO-HLIx
grep -src 'psb28-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>psb28-PRO-HLVI
grep -src 'psb28-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>psb28-PRO-LLIIxIII
grep -src 'psb28-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>psb28-PRO-LLIV
grep -src 'psb28-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>psb28-PRO-LLIx
grep -src 'psb28-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>psb28-SYN
grep -src 'psbA-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>psbA-PRO-HLII
grep -src 'psbA-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>psbA-PRO-HLIx
grep -src 'psbA-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>psbA-PRO-HLVI
grep -src 'psbA-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>psbA-PRO-LLIIxIII
grep -src 'psbA-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>psbA-PRO-LLIV
grep -src 'psbA-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>psbA-PRO-LLIx
grep -src 'psbA-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>psbA-SYN
grep -src 'PstB-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>PstB-PRO-HLII
grep -src 'PstB-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>PstB-PRO-HLIx
grep -src 'PstB-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>PstB-PRO-HLVI
grep -src 'PstB-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>PstB-PRO-LLIIxIII
grep -src 'PstB-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>PstB-PRO-LLIV
grep -src 'PstB-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>PstB-PRO-LLIx
grep -src 'PstB-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>PstB-SYN
grep -src 'purF-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>purF-PRO-HLII
grep -src 'purF-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>purF-PRO-HLIx
grep -src 'purF-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>purF-PRO-HLVI
grep -src 'purF-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>purF-PRO-LLIIxIII
grep -src 'purF-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>purF-PRO-LLIV
grep -src 'purF-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>purF-PRO-LLIx
grep -src 'purF-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>purF-SYN
grep -src 'recA-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>recA-PRO-HLII
grep -src 'recA-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>recA-PRO-HLIx
grep -src 'recA-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>recA-PRO-HLVI
grep -src 'recA-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>recA-PRO-LLIIxIII
grep -src 'recA-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>recA-PRO-LLIV
grep -src 'recA-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>recA-PRO-LLIx
grep -src 'recA-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>recA-SYN
grep -src 'SigB-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>SigB-PRO-LLIV
grep -src 'SigB-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>SigB-SYN
grep -src 'sodB-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>sodB-PRO-HLII
grep -src 'sodB-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>sodB-PRO-HLIx
grep -src 'sodB-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>sodB-PRO-HLVI
grep -src 'sodB-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>sodB-PRO-LLIIxIII
grep -src 'sodB-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>sodB-PRO-LLIV
grep -src 'sodB-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>sodB-PRO-LLIx
grep -src 'sodB-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>sodB-SYN
grep -src 'TcyC-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>TcyC-PRO-LLIIxIII
grep -src 'TcyN-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>TcyN-PRO-HLII
grep -src 'TcyN-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>TcyN-PRO-HLIx
grep -src 'TcyN-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>TcyN-PRO-LLIx
grep -src 'TcyN-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>TcyN-SYN
grep -src 'topA-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>topA-PRO-HLII
grep -src 'topA-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>topA-PRO-HLIx
grep -src 'topA-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>topA-PRO-HLVI
grep -src 'topA-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>topA-PRO-LLIIxIII
grep -src 'topA-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>topA-PRO-LLIV
grep -src 'topA-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>topA-PRO-LLIx
grep -src 'topA-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>topA-SYN
grep -src 'URA2-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>URA2-PRO-HLII
grep -src 'URA2-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>URA2-PRO-HLIx
grep -src 'URA2-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>URA2-PRO-HLVI
grep -src 'URA2-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>URA2-PRO-LLIIxIII
grep -src 'URA2-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>URA2-PRO-LLIV
grep -src 'URA2-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>URA2-PRO-LLIx
grep -src 'URA2-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>URA2-SYN
grep -src 'urtA-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>urtA-PRO-HLII
grep -src 'urtA-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>urtA-PRO-HLIx
grep -src 'urtA-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>urtA-PRO-HLVI
grep -src 'urtA-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>urtA-PRO-LLIIxIII
grep -src 'urtA-PRO-LLIV' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>urtA-PRO-LLIV
grep -src 'urtA-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>urtA-PRO-LLIx
grep -src 'urtA-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>urtA-SYN
grep -src 'YfeA-PRO-HLII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>YfeA-PRO-HLII
grep -src 'YfeA-PRO-HLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>YfeA-PRO-HLIx
grep -src 'YfeA-PRO-HLVI' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>YfeA-PRO-HLVI
grep -src 'YfeA-PRO-LLIIxIII' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>YfeA-PRO-LLIIxIII
grep -src 'YfeA-PRO-LLIx' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>YfeA-PRO-LLIx
grep -src 'YfeA-SYN' /data/gpfs02/sjgao/BUCE-SCS/2026-All-genes-read/* | awk -F: '$NF+0 > -1'>YfeA-SYN
